---
# This playbook just apply debops.dhcpd Role to a target node. 
- name: Infrastructure Services [DHCP server]
  hosts: target-node
  become: yes

  vars_files:
    - vars_dhcp.yml

  roles:
     - debops.dhcpd