---

# Do we need to set the static IP address for this server so rackHD knows how to contact or does rackHD send broadcast request
# We might need to set up a relay to a diff vlan for instances where nodes on different vlans need to access the dhcp server

dhcpd_mode: 'server'
dhcpd_ipversion: '4'
dhcpd_base_packages_map:
  'server': [ 'isc-dhcp-server' ]
dhcpd_server_options: '{{ "-" + dhcpd_ipversion }}'

dhcpd_authoritative: True
dhcpd_log_facility: 'local7'
dhcpd_interfaces: []
ansible_domain: paclabs.io

dhcpd_lease_time: '24'
dhcpd_global_default_lease_time: '{{ (((dhcpd_lease_time|int / 2) + 6) * 60 * 60)|round|int }}'
dhcpd_global_max_lease_time: '{{ (dhcpd_lease_time|int * 60 * 60)|round|int }}'

dhcpd_domain_name: '{{ ansible_domain }}'

# where to ask for DNS Server / dhcpd_dns_servers
ansible_default_ipv4.address: localhost

dhcpd_subnets:
 - subnet: '10.4.44.0'
   netmask: '255.255.255.0'
   routers: '10.4.44.1'
   pools:
     - range: '10.4.44.150 10.4.44.249'

# - subnet: '10.4.44.'
 #  netmask: '255.255.254.0'
  # routers: '10.4.44.93'
   #options: |
    # default-lease-time 300;
     #max-lease-time 7200;
   #pools:
    # - comment: "ls-db pool"
     #  range: '10.4.44.150 10.4.44.199'
