---

dhcpd_mode: 'server'
dhcpd_ipversion: '4'
dhcpd_base_packages_map:
  'server': [ 'isc-dhcp-server' ]
dhcpd_server_options: '{{ "-" + dhcpd_ipversion }}'

dhcpd_authoritative: True
dhcpd_log_facility: 'local7'
dhcpd_interfaces: []
ansible_domain: bellevuelab.isus.emc.com

dhcpd_lease_time: '24'
dhcpd_global_default_lease_time: '{{ (((dhcpd_lease_time|int / 2) + 6) * 60 * 60)|round|int }}'
dhcpd_global_max_lease_time: '{{ (dhcpd_lease_time|int * 60 * 60)|round|int }}'

dhcpd_domain_name: '{{ ansible_domain }}'

# where to ask for DNS Server / dhcpd_dns_servers
ansible_default_ipv4.address: 192.168.2.1

dhcpd_shared_networks:
  - name: 'ls-bulb-net'
    comment: "Remote shared network"
    subnets: '{{ dhcpd_subnets_local }}'
    options: |
      default-lease-time 600;
      max-lease-time 900;

dhcpd_subnets_local:
 - subnet: '192.168.2.0'
   netmask: '255.255.255.0'
   routers: [ '192.168.2.1' ]
   pools:
     - comment: "ls-web pool"
       range: '192.168.2.100 192.168.2.199'

 - subnet: '192.168.3.0'
   netmask: '255.255.255.0'
   routers: '192.168.3.1'
   options: |
     default-lease-time 300;
     max-lease-time 7200;
   pools:
     - comment: "ls-db pool"
       range: '192.168.3.100 192.168.3.199'
